import { Metadata } from 'next';

const POST_URL = 'https://frame-airdrop.vercel.app/api/frame';
const IMG_URL =
  'https://i.kym-cdn.com/entries/icons/original/000/031/544/cover13.jpg';

console.log('posturl', POST_URL);
const frameMetadata = {
  'fc:frame': 'vNext',
  'fc:frame:image': IMG_URL,
  'fc:frame:button:1': 'YEET',
  'fc:frame:button:2': 'YEET',
  'fc:frame:post_url': POST_URL,
};

export const metadata: Metadata = {
  title: 'Frame Airdrop',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Frame Airdrop',
    images: [IMG_URL],
  },
  other: {
    ...frameMetadata,
  },
};

export default function Home() {
  return (
    <>
      <main>YEET, YEET, YEET, YEET, YEET</main>
    </>
  );
}
